define(
{
    "reducedVersion":true,
    "toc":[
        {
            "heading":"Table of Contents",
            "topics":[
                {
                    "title":"List of Tables",
                    "href":"lot.html"
                },
                {
                    "title":"Title and Copyright Information",
                    "href":"index.html"
                },
                {
                    "title":"Preface",
                    "href":"preface.html#GUID-9217AAF2-7E10-4BB6-858B-7641259ED6CA"
                },
                {
                    "title":"Changes in This Release for Oracle Providers for ASP.NET Developer's Guide",
                    "href":"release_changes.html#GUID-22054446-D596-4B10-A874-AD09A5ED9FA2"
                },
                {
                    "title":"<span class=\"secnum\">1 </span> Introduction to Oracle Providers for ASP.NET",
                    "href":"Intro.html#GUID-030BA31F-5E6C-4598-B305-EBBEDF8E3677",
                    "topics":[
                        {
                            "title":"Overview of Oracle Providers for ASP.NET",
                            "href":"IntroOverview.html#GUID-41F6EA08-AB9F-462C-A558-A2EB523811B7"
                        },
                        {
                            "title":"Oracle Providers for ASP.NET Assembly",
                            "href":"IntroAssemblyandClassList.html#GUID-1BC65A24-702F-48B4-9A32-F3C73E6E993A"
                        },
                        {
                            "title":"System Requirements",
                            "href":"IntroSystemRequirements.html#GUID-263669E3-EE17-44FD-B750-048CE4234AC1"
                        },
                        {
                            "title":"Oracle Providers for ASP.NET Installation",
                            "href":"IntroInstallation.html#GUID-6A5EC668-F220-4131-A3FD-231A9E3E4DC1"
                        },
                        {
                            "title":"Upgrading Oracle Providers for ASP.NET",
                            "href":"IntroUpgrading.html#GUID-E71BF201-DB99-4BC1-BA08-C3C0BEA13AE6"
                        },
                        {
                            "title":"File Locations After Installation",
                            "href":"IntroFileLocations.html#GUID-23A5DC65-7745-48B6-8C3F-D733FFF7279C"
                        },
                        {
                            "title":"Oracle Providers for ASP.NET Object References",
                            "href":"IntroObjectreferences.html#GUID-7588D373-7477-448E-8213-A737B71C8924"
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">2 </span> OracleMembershipProvider",
                    "href":"OracleMembershipProvider.html#GUID-CD514BAB-DD1D-4292-803F-F07F2F1E90DE",
                    "topics":[
                        {
                            "title":"OracleMembershipProvider Class",
                            "href":"OracleMembershipProviderClass.html#GUID-60D86D80-1FBA-4076-9D69-CBABB88349CC",
                            "topics":[
                                {
                                    "title":"OracleMembershipProvider Members",
                                    "href":"OracleMembershipProviderMembers.html#GUID-E82F4D76-B034-427C-8337-7AE8515AD9F5"
                                },
                                {
                                    "title":"OracleMembershipProvider Constructors",
                                    "href":"MembershipProviderConstructors.html#GUID-41B17111-1F42-4DBF-97C3-ED605B612129",
                                    "topics":[
                                        {
                                            "title":"OracleMembershipProvider()",
                                            "href":"MembershipProviderCtor1.html#GUID-74AB1E24-F889-4214-B425-669A9062FDA1"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleMembershipProvider Static Methods",
                                    "href":"MembershipProviderStaticMethods.html#GUID-DB9711D0-0CD1-41F1-B18C-9C97E2675339"
                                },
                                {
                                    "title":"OracleMembershipProvider Public Properties",
                                    "href":"MembershipProviderPublicProperties.html#GUID-FD387352-EA49-402A-821C-75221AB0187E",
                                    "topics":[
                                        {
                                            "title":"ApplicationName",
                                            "href":"MembershipProviderApplicationName.html#GUID-0991880E-C907-4E22-885F-BCD7E51136D8"
                                        },
                                        {
                                            "title":"CommandTimeout",
                                            "href":"MembershipProviderCommandTimeout.html#GUID-4AC286F1-FA42-442B-8E92-FE750A0D1931"
                                        },
                                        {
                                            "title":"EnablePasswordReset",
                                            "href":"MembershipProviderEnablePasswordReset.html#GUID-5519AD21-8B3C-45B4-A354-D3CBB9CD7B56"
                                        },
                                        {
                                            "title":"EnablePasswordRetrieval",
                                            "href":"MembershipProviderEnablePasswordRetrieval.html#GUID-71D8302B-4C59-4210-8C23-81FF5ED33EAF"
                                        },
                                        {
                                            "title":"MaxInvalidPasswordAttempts",
                                            "href":"MembershipProviderMaxInvalidPasswordAttempts.html#GUID-B59FDFD5-D5E4-4DA2-BC9A-3C0E95100095"
                                        },
                                        {
                                            "title":"MinRequiredNonAlphanumericCharacters",
                                            "href":"MembershipProviderMinRequiredNonAlphanumericCharacters.html#GUID-D2555FC7-C061-438D-B8DC-93A35010C344"
                                        },
                                        {
                                            "title":"MinRequiredPasswordLength",
                                            "href":"MembershipProviderMinRequiredPasswordLength.html#GUID-1032C820-956A-47B5-88B8-63ECAF969F15"
                                        },
                                        {
                                            "title":"PasswordAttemptWindow",
                                            "href":"MembershipProviderPasswordAttemptWindow.html#GUID-E2B4400B-452F-41CE-9BD9-2D8F4058CB06"
                                        },
                                        {
                                            "title":"PasswordCompatMode",
                                            "href":"MembershipProviderPasswordCompatMode.html#GUID-5EF9242C-47D5-465F-BC09-480D7F7EC41D"
                                        },
                                        {
                                            "title":"PasswordFormat",
                                            "href":"MembershipProviderPasswordFormat.html#GUID-8529959D-ED2A-4C49-933A-93A0DF1B9201"
                                        },
                                        {
                                            "title":"PasswordStrengthRegularExpression",
                                            "href":"MembershipProviderPasswordStrengthRegularExpression.html#GUID-F086D708-D738-4770-9AB0-859CEA7E7036"
                                        },
                                        {
                                            "title":"RequiresQuestionAndAnswer",
                                            "href":"MembershipProviderRequiresQuestionAndAnswer.html#GUID-6F333570-BE23-4766-8490-DE68B7E8139B"
                                        },
                                        {
                                            "title":"RequiresUniqueEmail",
                                            "href":"MembershipProviderRequiresUniqueEmail.html#GUID-FFC929DF-43C0-42B3-B05C-3CEC3751799A"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleMembershipProvider Public Methods",
                                    "href":"MembershipProviderPublicMethods.html#GUID-A4D8DB58-3368-4B5C-B3AC-93379782B043",
                                    "topics":[
                                        {
                                            "title":"ChangePassword",
                                            "href":"MembershipProviderChangePassword.html#GUID-EFF6603D-0661-440B-92FD-2662711EAAF4"
                                        },
                                        {
                                            "title":"ChangePasswordQuestionAndAnswer",
                                            "href":"MembershipProviderChangePasswordQuestionAndAnswer.html#GUID-49FA8259-81B0-463A-85EC-0709ABF5C7C6"
                                        },
                                        {
                                            "title":"CreateUser",
                                            "href":"MembershipProviderCreateUser.html#GUID-599111D9-5452-4707-ACD3-45D067958EA8"
                                        },
                                        {
                                            "title":"DeleteUser",
                                            "href":"MembershipProviderDeleteUser.html#GUID-DAEE2CC7-F1BE-495D-BC7C-19D312FA1110"
                                        },
                                        {
                                            "title":"FindUsersByEmail",
                                            "href":"MembershipProviderFindUsersByEmail.html#GUID-44A17CB2-BA55-4552-8171-C4B1059C2501"
                                        },
                                        {
                                            "title":"FindUsersByName",
                                            "href":"MembershipProviderFindUsersByName.html#GUID-ED1F2D9F-A04E-4426-A29C-6400A388972D"
                                        },
                                        {
                                            "title":"GeneratePassword",
                                            "href":"MembershipProviderGeneratePassword.html#GUID-23856CCE-CFAE-4E75-A07A-5AC8207A365A"
                                        },
                                        {
                                            "title":"GetAllUsers",
                                            "href":"MembershipProviderGetAllUsers.html#GUID-29F7A799-9B1F-4BB3-A4ED-66BB4BDAC66F"
                                        },
                                        {
                                            "title":"GetNumberOfUsersOnline",
                                            "href":"MembershipProviderGetNumberOfUsersOnline.html#GUID-F1DACC3D-FA73-4C06-B45E-6E2F82C0836F"
                                        },
                                        {
                                            "title":"GetPassword",
                                            "href":"MembershipProviderGetPassword.html#GUID-FC29A672-68F9-4154-A15E-19ADCC8D50F1"
                                        },
                                        {
                                            "title":"GetUser",
                                            "href":"MembershipProviderGetUserOverloads.html#GUID-B5074520-93A4-4722-97E1-012E233239DB"
                                        },
                                        {
                                            "title":"GetUser(Object, bool)",
                                            "href":"MembershipProviderGetUser1.html#GUID-2A4E3F0A-90AA-4BB5-BE13-741E5A7D2A2F"
                                        },
                                        {
                                            "title":"GetUser(string, bool)",
                                            "href":"MembershipProviderGetUser2.html#GUID-80020F6E-7923-4FEC-A142-43C77528229B"
                                        },
                                        {
                                            "title":"GetUserNameByEmail",
                                            "href":"MembershipProviderGetUserNameByEmail.html#GUID-2925B7E8-65BA-4FC9-9079-A7487F7F83E3"
                                        },
                                        {
                                            "title":"Initialize",
                                            "href":"MembershipProviderInitialize.html#GUID-405BA65B-23E9-486B-AFFC-2CF95C991609"
                                        },
                                        {
                                            "title":"ResetPassword",
                                            "href":"MembershipProviderResetPassword.html#GUID-439C28DF-63D5-4FBB-9012-EED8DA62C62C"
                                        },
                                        {
                                            "title":"UnlockUser",
                                            "href":"MembershipProviderUnlockUser.html#GUID-5582A8C9-E857-4530-A649-F0F34AEA5F83"
                                        },
                                        {
                                            "title":"UpdateUser",
                                            "href":"MembershipProviderUpdateUser.html#GUID-B7EE7AE8-2334-46E1-A126-D43533044C33"
                                        },
                                        {
                                            "title":"ValidateUser",
                                            "href":"MembershipProviderValidateUser.html#GUID-A1859655-5E6B-47B8-A8A1-00C1794FBAA0"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleMembershipProvider Public Events",
                                    "href":"MembershipProviderPublicEvents.html#GUID-8DB96AAA-4CF8-4919-8F4C-7E724D0CBC65"
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">3 </span> OracleRoleProvider",
                    "href":"OracleRoleProvider.html#GUID-5753FD60-CEA8-4141-B3AE-AC093E2977AA",
                    "topics":[
                        {
                            "title":"OracleRoleProvider Class",
                            "href":"OracleRoleProviderClass.html#GUID-68D5BE92-2C97-4BB6-9134-8D060097A89A",
                            "topics":[
                                {
                                    "title":"OracleRoleProvider Members",
                                    "href":"OracleRoleProviderMembers.html#GUID-F8DC2F31-C974-42E2-A048-F121DE662C5D"
                                },
                                {
                                    "title":"OracleRoleProvider Constructors",
                                    "href":"RoleProviderConstructors.html#GUID-34690AA7-FD9D-48C2-8949-E3E663E199A5",
                                    "topics":[
                                        {
                                            "title":"OracleRoleProvider()",
                                            "href":"RoleProviderCtor1.html#GUID-C165E363-2EFC-4260-BEA2-75F940E92D5A"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleRoleProvider Static Methods",
                                    "href":"RoleProviderStaticMethods.html#GUID-963F816A-3337-4D86-82D9-75EDE6671417"
                                },
                                {
                                    "title":"OracleRoleProvider Public Properties",
                                    "href":"RoleProviderPublicProperties.html#GUID-F76980E7-33C4-4898-851F-8A6203464DC6",
                                    "topics":[
                                        {
                                            "title":"ApplicationName",
                                            "href":"RoleProviderApplicationName.html#GUID-E42A96FE-8843-4636-BFFE-EC195BE50513"
                                        },
                                        {
                                            "title":"CommandTimeout",
                                            "href":"RoleProviderCommandTimeout.html#GUID-4D0E5A6E-E943-453F-B128-EA67D8176D9E"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleRoleProvider Public Methods",
                                    "href":"RoleProviderPublicMethods.html#GUID-EB94957A-6B1B-434D-98BB-CE03437CBD00",
                                    "topics":[
                                        {
                                            "title":"AddUsersToRoles",
                                            "href":"RoleProviderAddUsersToRoles.html#GUID-192BE9F4-4E05-4CC3-A89E-3527E0AAD90D"
                                        },
                                        {
                                            "title":"CreateRole",
                                            "href":"RoleProviderCreateRole.html#GUID-5FE58354-50AA-486B-B064-2982751662E3"
                                        },
                                        {
                                            "title":"DeleteRole",
                                            "href":"RoleProviderDeleteRole.html#GUID-00E341AC-B451-439E-8CC4-791DB5B74055"
                                        },
                                        {
                                            "title":"FindUsersInRole",
                                            "href":"RoleProviderFindUsersInRole.html#GUID-DC2AE9FD-B2E3-4A1C-86BC-7E07BA523953"
                                        },
                                        {
                                            "title":"GetAllRoles",
                                            "href":"RoleProviderGetAllRoles.html#GUID-A38E7F50-4EB3-4227-B5E0-FFCDE69B2BD1"
                                        },
                                        {
                                            "title":"GetRolesForUser",
                                            "href":"RoleProviderGetRolesForUsers.html#GUID-BCD4A923-91F7-4077-9E9F-37DA787C5EAB"
                                        },
                                        {
                                            "title":"GetUsersInRole",
                                            "href":"RoleProviderGetUsersInRole.html#GUID-EF66E235-BA4C-4DA9-96E3-28E28DA76C4F"
                                        },
                                        {
                                            "title":"Initialize",
                                            "href":"RoleProviderInitialize.html#GUID-ECBE6DC0-63FF-4549-9172-F683E58A274E"
                                        },
                                        {
                                            "title":"IsUserInRole",
                                            "href":"RoleProviderIsUserInRole.html#GUID-EBABB913-935B-4F5A-9547-AC172FA60EFF"
                                        },
                                        {
                                            "title":"RemoveUsersFromRoles",
                                            "href":"RoleProviderRemoveUsersFromRoles.html#GUID-D9E27E28-2FA1-4363-9854-56BF8FA3C285"
                                        },
                                        {
                                            "title":"RoleExists",
                                            "href":"RoleProviderRoleExists.html#GUID-7D53EB67-F0DD-4A57-82A2-6A1B2DC9BA3F"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">4 </span> OracleSiteMapProvider",
                    "href":"OracleSiteMapProvider.html#GUID-941FB937-0F6F-40A9-BDB3-FD7247801E39",
                    "topics":[
                        {
                            "title":"OracleSiteMapProvider Class",
                            "href":"OracleSiteMapProviderClass.html#GUID-06003F10-22D6-479E-A441-16F14D8B5ADC",
                            "topics":[
                                {
                                    "title":"OracleSiteMapProvider Members",
                                    "href":"OracleSiteMapProviderMembers.html#GUID-3AE2A7A8-F9F5-40EB-8772-3FEA6717B99D"
                                },
                                {
                                    "title":"OracleSiteMapProvider Constructors",
                                    "href":"SiteMapProviderConstructors.html#GUID-08F30C83-1ECA-40E7-A810-F074F45A1EBD",
                                    "topics":[
                                        {
                                            "title":"OracleSiteMapProvider()",
                                            "href":"SiteMapProviderCtor1.html#GUID-1DD343AB-0267-4D5A-A288-AAB440942E57"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleSiteMapProvider Static Methods",
                                    "href":"SiteMapProviderStaticMethods.html#GUID-0D4B0076-52C0-4F9D-B2FB-DB0E7C747A38"
                                },
                                {
                                    "title":"OracleSiteMapProvider Public Properties",
                                    "href":"SiteMapProviderPublicProperties.html#GUID-622632F2-DC6D-42FA-A44A-76B9AED44F97",
                                    "topics":[
                                        {
                                            "title":"ApplicationName",
                                            "href":"SiteMapApplicationName.html#GUID-7719852A-4CBC-4D9D-9605-91FA86A56F4E"
                                        },
                                        {
                                            "title":"CommandTimeout",
                                            "href":"SiteMapCommandTimeout.html#GUID-6AE64A41-418E-439F-95DA-0FE1E33C00A1"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleSiteMapProvider Public Methods",
                                    "href":"SiteMapProviderPublicMethods.html#GUID-EAD99FD9-DD77-4CA9-A84C-E36C4CDDED50",
                                    "topics":[
                                        {
                                            "title":"BuildSiteMap",
                                            "href":"SiteMapProviderBuildSiteMap.html#GUID-EED5E82E-650A-46EA-900C-BDF00161A3A4"
                                        },
                                        {
                                            "title":"Dispose",
                                            "href":"SiteMapProviderDispose.html#GUID-DDC746EB-9EDC-41B5-829D-8688D2634F5B"
                                        },
                                        {
                                            "title":"Initialize",
                                            "href":"SiteMapProviderInitialize.html#GUID-A2D4CDEF-FB08-4020-B942-AE31F67F16AD"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">5 </span> OracleSessionStateStore",
                    "href":"OracleSessionStateStore.html#GUID-2A422426-53B6-4755-ACD4-0AC084AB2D80",
                    "topics":[
                        {
                            "title":"OracleSessionStateStore Class",
                            "href":"OracleSessionStateStoreClass.html#GUID-813F8883-D15E-4430-BC24-0D6A0E760121",
                            "topics":[
                                {
                                    "title":"OracleSessionStateStore Members",
                                    "href":"OracleSessionStateStoreMembers.html#GUID-4845FF34-34CE-4B7E-819C-17146DDF3B84"
                                },
                                {
                                    "title":"OracleSessionStateStore Constructors",
                                    "href":"OracleSessionStateStoreConstructors.html#GUID-43C4FEB9-A91A-4084-B76C-E6B136ABC1EA",
                                    "topics":[
                                        {
                                            "title":"OracleSessionStateStore()",
                                            "href":"SessionStateStoreCtor1.html#GUID-AD432343-4190-4B84-84F8-051AB0B157C5"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleSessionStateStore Public Properties",
                                    "href":"SessionStateStorePublicProperties.html#GUID-0B04CB6A-864E-410E-8971-8A89A9D6E6EA",
                                    "topics":[
                                        {
                                            "title":"CommandTimeout",
                                            "href":"SessionStateStoreCommandTimeout.html#GUID-B0413190-017A-48AD-B19B-AEDBE57648FF"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleSessionStateStore Public Methods",
                                    "href":"SessionStateStorePublicMethods.html#GUID-008D89A0-2C81-4DBA-9A0F-270C58168709",
                                    "topics":[
                                        {
                                            "title":"CreateNewStoreData",
                                            "href":"SessionStateStoreCreateNewStoreData.html#GUID-70AB5F9E-461F-4A0D-9C47-2CE0ECBDE430"
                                        },
                                        {
                                            "title":"CreateUninitializedItem",
                                            "href":"SessionStateStoreCreateUninitializedItem.html#GUID-BC609DDF-0EEB-428A-9CF6-63E1FE9FE60A"
                                        },
                                        {
                                            "title":"Dispose",
                                            "href":"SessionStateStoreDispose.html#GUID-3D23FEC2-BE1A-4EDD-AD7F-7B0C714E5F27"
                                        },
                                        {
                                            "title":"EndRequest",
                                            "href":"SessionStateStoreEndRequest.html#GUID-12F6F847-8A0E-445F-9F6E-E51BCEA9FB9B"
                                        },
                                        {
                                            "title":"GetItem",
                                            "href":"SessionStateStoreGetItem.html#GUID-0C5FD72D-BDE0-411B-AB5C-F7CFDF852AEC"
                                        },
                                        {
                                            "title":"GetItemExclusive",
                                            "href":"SessionStateStoreGetItemExclusive.html#GUID-C368F494-7693-45D3-A3A2-93319D5B07D2"
                                        },
                                        {
                                            "title":"Initialize",
                                            "href":"SessionStateStoreInitialize.html#GUID-BEBFDD81-E88B-4EDE-8301-CE943709DA6F"
                                        },
                                        {
                                            "title":"InitializeRequest",
                                            "href":"SessionStateStoreInitializeRequest.html#GUID-492F71A1-12BA-4043-81F1-3FF0E0D5199E"
                                        },
                                        {
                                            "title":"ReleaseItemExclusive",
                                            "href":"SessionStateStoreReleaseItemExclusive.html#GUID-6B2D1457-328A-44A3-A9DC-F7752C93A4F4"
                                        },
                                        {
                                            "title":"RemoveItem",
                                            "href":"SessionStateStoreRemoveItem.html#GUID-CDCE527D-F498-46E0-9EA5-E443482D9051"
                                        },
                                        {
                                            "title":"ResetItemTimeout",
                                            "href":"SessionStateStoreResetItemTimeout.html#GUID-A4FEA02B-BAC7-40C6-BEFB-4F107282CB8F"
                                        },
                                        {
                                            "title":"SetAndReleaseItemExclusive",
                                            "href":"SessionStateStoreSetAndReleaseItemExclusive.html#GUID-734682E0-FCB1-4984-A95C-A1715AE3AB7A"
                                        },
                                        {
                                            "title":"SetItemExpireCallback",
                                            "href":"SessionStateStoreSetItemExpireCallback.html#GUID-97B3E1F8-A72A-4C0A-8AD2-B3AFDDA8232E"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">6 </span> OracleProfileProvider",
                    "href":"OracleProfileProvider.html#GUID-A5D7476D-3921-4B62-A980-35DDC292CB40",
                    "topics":[
                        {
                            "title":"OracleProfileProvider Class",
                            "href":"OracleProfileProviderClass.html#GUID-4B01F949-69E7-4B37-A189-4395D96D585F",
                            "topics":[
                                {
                                    "title":"OracleProfileProvider Members",
                                    "href":"OracleProfileProviderMembers.html#GUID-8F40D27F-C825-4291-BB83-6F44A3EBF7A6"
                                },
                                {
                                    "title":"OracleProfileProvider Constructors",
                                    "href":"ProfileProviderConstructors.html#GUID-10DD82F1-0D9A-4BB8-8DE8-5B9CAE8426B1",
                                    "topics":[
                                        {
                                            "title":"OracleProfileProvider()",
                                            "href":"ProfileProviderCtor1.html#GUID-C19915CB-DA72-4FB7-9FF0-2C14B797EC0A"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleProfileProvider Static Methods",
                                    "href":"ProfileProviderStaticMethods.html#GUID-EB1B0D4B-CC09-4046-943B-809441EE7032"
                                },
                                {
                                    "title":"OracleProfileProvider Public Properties",
                                    "href":"ProfileProviderPublicProperties.html#GUID-49C61245-DDDE-4B8B-A3E1-633A4CF8270A",
                                    "topics":[
                                        {
                                            "title":"ApplicationName",
                                            "href":"ProfileProviderApplicationName.html#GUID-9B1427BA-6301-4E08-8357-2F680D02FA5B"
                                        },
                                        {
                                            "title":"CommandTimeout",
                                            "href":"ProfileProviderCommandTimeout.html#GUID-4B19FA6B-F6FC-4890-8051-4FEFED756273"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleProfileProvider Public Methods",
                                    "href":"ProfileProviderPublicMethods.html#GUID-6EA56170-0389-4422-96C8-6000DF3B79E6",
                                    "topics":[
                                        {
                                            "title":"DeleteInactiveProfiles",
                                            "href":"ProfileProviderDeleteInactiveProfiles.html#GUID-DD911CDB-EE39-42A2-86DE-5D492726CB98"
                                        },
                                        {
                                            "title":"DeleteProfiles",
                                            "href":"ProfileProviderDeleteProfilesOverloads.html#GUID-D976F7C3-FCC4-46F1-AD34-B0AFE487F52A"
                                        },
                                        {
                                            "title":"DeleteProfiles(ProfileInfoCollection)",
                                            "href":"ProfileProviderDeleteProfiles1.html#GUID-40DA6385-81AB-44DB-826F-44AA013489A7"
                                        },
                                        {
                                            "title":"DeleteProfiles(string[])",
                                            "href":"ProfileProviderDeleteProfiles2.html#GUID-48A67182-4817-4A88-9662-17CC99B1C749"
                                        },
                                        {
                                            "title":"FindInactiveProfilesByUserName",
                                            "href":"ProfileProviderFindInactiveProfilesByUserName.html#GUID-E1C576C9-2936-4BDE-9076-46ED0227CA6B"
                                        },
                                        {
                                            "title":"FindProfilesByUserName",
                                            "href":"ProfileProviderFindProfilesByUserName.html#GUID-A7AC8FC5-1681-4867-8CC0-9E4E8A1AD786"
                                        },
                                        {
                                            "title":"GetAllInactiveProfiles",
                                            "href":"ProfileProviderGetAllInactiveProfiles.html#GUID-6A22B111-9A04-4D1D-81AE-02751D339666"
                                        },
                                        {
                                            "title":"GetAllProfiles",
                                            "href":"ProfileProviderGetAllProfilesMethod.html#GUID-4024E037-19C6-416B-ACDE-DE674290BF1E"
                                        },
                                        {
                                            "title":"GetNumberOfInactiveProfiles",
                                            "href":"ProfileProviderGetNumberOfInactiveProfiles.html#GUID-571D43CA-C755-4351-9161-B1BCDB2BE819"
                                        },
                                        {
                                            "title":"GetPropertyValues",
                                            "href":"ProfileProviderGetPropertyValues.html#GUID-191F77A1-6A01-4929-9957-02C33EF6B2B4"
                                        },
                                        {
                                            "title":"Initialize",
                                            "href":"ProfileProviderInitialize.html#GUID-2EFDAFB8-C554-40B3-AF59-0BD129CB2F68"
                                        },
                                        {
                                            "title":"SetPropertyValues",
                                            "href":"ProfileProviderSetPropertyValues.html#GUID-A2BF4BC2-051D-44DC-8414-822A630F484F"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">7 </span> OracleWebEventProvider",
                    "href":"OracleWebEventProvider.html#GUID-EF108999-9856-4C10-8240-03361486796B",
                    "topics":[
                        {
                            "title":"OracleWebEventProvider Class",
                            "href":"OracleWebEventProviderClass.html#GUID-1E9F03EC-D526-462F-A6DF-1DE9C52AD6BC",
                            "topics":[
                                {
                                    "title":"OracleWebEventProvider Members",
                                    "href":"OracleWebEventProviderMembers.html#GUID-AE164E47-1132-4656-853E-9D7C593D0278"
                                },
                                {
                                    "title":"OracleWebEventProvider Constructors",
                                    "href":"WebEventProviderConstructors.html#GUID-C4C0BEE3-15F9-48A9-B3DA-7FF898E136FF",
                                    "topics":[
                                        {
                                            "title":"OracleWebEventProvider()",
                                            "href":"WebEventProviderCtor1.html#GUID-E6A73A68-B5C0-4D0A-877F-AF0F3487496F"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleWebEventProvider Static Methods",
                                    "href":"WebEventProviderStaticMethods.html#GUID-F6007C4A-B29B-40E6-A5EE-97292F561A4F"
                                },
                                {
                                    "title":"OracleWebEventProvider Public Properties",
                                    "href":"WebEventProviderPublicProperties.html#GUID-49357E59-E6F3-44FF-9F38-14D6F50B85EF",
                                    "topics":[
                                        {
                                            "title":"CommandTimeout",
                                            "href":"WebEventProviderCommandTimeout.html#GUID-3F37480F-211A-4171-BDCF-C54C421883A8"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleWebEventProvider Public Methods",
                                    "href":"WebEventProviderPublicMethods.html#GUID-9DB117A9-E01C-4D4F-BB3B-727F907C9FD1",
                                    "topics":[
                                        {
                                            "title":"Initialize",
                                            "href":"WebEventProviderInitialize.html#GUID-02B57C25-59E7-467F-B9E2-F12B21A9C3D9"
                                        },
                                        {
                                            "title":"ProcessEvent",
                                            "href":"WebEventProviderProcessEvent.html#GUID-ACC7E596-1C81-4F20-8E38-9E45F5E3A9B0"
                                        },
                                        {
                                            "title":"ProcessEventFlush",
                                            "href":"WebEventProviderProcessEventFlush.html#GUID-7A62832D-2903-448A-B0CB-D165BADFB3FF"
                                        },
                                        {
                                            "title":"Shutdown",
                                            "href":"WebEventProviderShutdown.html#GUID-3109C870-C3BE-418A-85AD-34D81783CDED"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">8 </span> OraclePersonalizationProvider",
                    "href":"OraclePersonalizationProvider.html#GUID-1FD13872-9C31-44CE-863D-66C0DEDAEF6C",
                    "topics":[
                        {
                            "title":"OraclePersonalizationProvider Class",
                            "href":"OraclePersonalizationProviderClass.html#GUID-E8181200-E3E8-4266-A262-7037B87C7384",
                            "topics":[
                                {
                                    "title":"OraclePersonalizationProvider Members",
                                    "href":"OraclePersonalizationProviderMembers.html#GUID-02689E4F-BADA-4971-905E-0680D8168B67"
                                },
                                {
                                    "title":"OraclePersonalizationProvider Constructors",
                                    "href":"PersonalizationProviderConstructors.html#GUID-E6D786A1-AF36-4553-AF2C-02C77BD8686E",
                                    "topics":[
                                        {
                                            "title":"OraclePersonalizationProvider()",
                                            "href":"PersonalizationProviderCtor1.html#GUID-BF296DF9-A68F-48A4-9A4A-4A0C197E8C0A"
                                        }
                                    ]
                                },
                                {
                                    "title":"OraclePersonalizationProvider Static Methods",
                                    "href":"PersonalizationProviderStaticMethods.html#GUID-7D877C5B-B0EC-457D-9131-9A48458EE050"
                                },
                                {
                                    "title":"OraclePersonalizationProvider Public Properties",
                                    "href":"PersonalizationProviderPublicProperties.html#GUID-D1C62718-9F48-490C-A9EB-5FE058349DF7",
                                    "topics":[
                                        {
                                            "title":"ApplicationName",
                                            "href":"PersonalizationProviderApplicationName.html#GUID-9112B703-5E15-4B70-BAF4-7E5561CE0EBF"
                                        },
                                        {
                                            "title":"CommandTimeout",
                                            "href":"PersonalizationProviderCommandTimeout.html#GUID-B521C3F9-0033-48F0-99E7-7ED6473DB496"
                                        }
                                    ]
                                },
                                {
                                    "title":"OraclePersonalizationProvider Public Methods",
                                    "href":"PersonalizationProviderPublicMethods.html#GUID-19B5F1D6-2155-4455-BD1C-E7B6EA73ADBE",
                                    "topics":[
                                        {
                                            "title":"FindState",
                                            "href":"PersonalizationProviderFindState.html#GUID-22709AEA-61C4-4159-BA20-AE8B8332C2E9"
                                        },
                                        {
                                            "title":"GetCountOfState",
                                            "href":"PersonalizationProviderGetCountOfState.html#GUID-A3815F66-95D0-4ED7-A169-E839D30BBFB6"
                                        },
                                        {
                                            "title":"Initialize",
                                            "href":"PersonalizationProviderInitialize.html#GUID-E3CCDAB8-E00B-4142-BF00-C33A85C5834A"
                                        },
                                        {
                                            "title":"ResetState",
                                            "href":"PersonalizationProviderResetState.html#GUID-64A618D0-EDB8-41E9-8D2C-6D79ADFF25BD"
                                        },
                                        {
                                            "title":"ResetUserState",
                                            "href":"PersonalizationProviderResetUserState.html#GUID-BA0E75E0-B0BF-46CC-B202-230F4FB4802A"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"<span class=\"secnum\">9 </span> OracleCacheDependency Provider",
                    "href":"OracleCacheDependency-Provider.html#GUID-38F1EC23-2733-452C-9D32-9E88A36B106C",
                    "topics":[
                        {
                            "title":"OracleCacheDependency Class",
                            "href":"OracleCacheDependencyClass.html#GUID-09B45C25-584A-473E-8E29-6EE6FCB7213D",
                            "topics":[
                                {
                                    "title":"OracleCacheDependency Members",
                                    "href":"OracleCacheDependencyMembers.html#GUID-F9A95E98-4CB9-4A2A-A92F-DE0361BBA944"
                                },
                                {
                                    "title":"OracleCacheDependency Constructors",
                                    "href":"CacheDependencyConstructors.html#GUID-0EDC936F-2114-4F5C-84BD-062BAE19AD18",
                                    "topics":[
                                        {
                                            "title":"OracleCacheDependency(OracleCommand)",
                                            "href":"CacheDependencyCtor1.html#GUID-15C99FC2-603B-4F22-8714-905123C2577D"
                                        }
                                    ]
                                },
                                {
                                    "title":"OracleCacheDependency Properties",
                                    "href":"CacheDependencyProperties.html#GUID-F21C084D-3BAA-4129-B729-B51E4A07824D"
                                },
                                {
                                    "title":"OracleCacheDependency Methods",
                                    "href":"CacheDependencyMethods.html#GUID-0DB35839-4BE1-4832-9C04-E0C17A59DE5C",
                                    "topics":[
                                        {
                                            "title":"GetUniqueID",
                                            "href":"CacheDependencyGetUniqueID.html#GUID-A1B37C38-C856-455B-8985-9D1FE0E154B7"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"Index",
                    "href":"book-index.html"
                }
            ]
        }
    ]
});